-- Outbound leads: prospect-safe one-line finding for cold email personalization.
-- Generated by the ICP scorer (lib/outbound/score.ts) during enrichment, so it is
-- always present by the time a lead is pushed to Instantly. Maps to the
-- {{audit_finding}} merge field in the cold email sequence. Distinct from
-- icp_reasoning, which is internal scoring rationale and not prospect-safe.

alter table public.outbound_leads
  add column if not exists audit_finding text;

comment on column public.outbound_leads.audit_finding is
  'One prospect-safe sentence in Verve voice naming the lead''s most compelling gap. Feeds the {{audit_finding}} merge field in cold email. Generated at scoring time.';
